### ISSUE TITLE
upper limit of records per file given to 3_Ingest: 3000

### ISSUE THREAD

**Issue by AndyElliottCRL** [Center-for-Research-Libraries/2_Preparation#4]
Confluence page with related discussions: https://workspace.crl.edu/display/PP/PAPR+Data+Preparation 
For now, say num_records_upper_limit = 3000 
So that the Putty session doesn't time out, and loads in general don't take excessive time while attended by a human, the 2_Preparation MRK/MRC output files should not exceed num_records_upper_limit.  From timing with a large Hathi file Aug. 2021, 3000 records should take less than one hour (Confluence link). 

For files from 1_Validation over num_records_upper_limit in size, the 2_Preparation scripts should output multiple files of num_records_upper_limit each, with '.a.','.b.', etc. appended to the file name like 
- OCLC_SYM.20211231.a.mrk
- OCLC_SYM.20211231.b.mrk
- OCLC_SYM.20211231.c.mrk
- ...
- OCLC_SYM.20211231.z.mrk
- OCLC_SYM.20211231.aa.mrk
- OCLC_SYM.20211231.ab.mrk
- OCLC_SYM.20211231.ac.mrk
- ...
- OCLC_SYM.20211231.az.mrk

**Comment by AndyElliottCRL** [comment]
@tmoss if you can verify that this record limit is in the code, we can close this.  You should be able to push those changes if they're not in the repo already. Please add a comment in this thread about where in the code the limit is located, so we can change it if we need to.  File name and function name should be good enough to find it, don't bother with line numbers that will just change. Thanks!

**Comment by tmoss-crl** [comment]
convert_to_mrk/convert_to_mrk.py
class LHR_writer
variable max_number_of_records
